"""Email relation with report

Revision ID: 007a6a6e7acd
Revises: 819c8c6698fd
Create Date: 2025-07-14 11:47:50.360564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '007a6a6e7acd'
down_revision: Union[str, None] = '819c8c6698fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('report_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'emails', 'reports', ['report_id'], ['id'])
    op.alter_column('organizations', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'report_id')
    # ### end Alembic commands ###
