"""Separate logout config to avoid overwriting it

Revision ID: 6ab7103717b1
Revises: 3fe6a8f53543
Create Date: 2025-07-21 02:48:11.237543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6ab7103717b1'
down_revision: Union[str, None] = '3fe6a8f53543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('logout_config', sa.JSON(), nullable=True, comment='Contains the xpaths to logout from paywalled newspapers'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'logout_config')
    # ### end Alembic commands ###
