"""Store date of last llm login attempt

Revision ID: db3d4934b5cf
Revises: 3fe6a8f53543
Create Date: 2025-07-21 04:58:32.244044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'db3d4934b5cf'
down_revision: Union[str, None] = '3fe6a8f53543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('llm_login_attempt', sa.TIMESTAMP(timezone=True), nullable=True, comment='Last time the LLM approach was attempted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'llm_login_attempt')
    # ### end Alembic commands ###
