"""add_report_id_to_email_conversations

Revision ID: de3c17bebf87
Revises: 819c8c6698fd
Create Date: 2025-07-13 23:28:15.857248

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de3c17bebf87"
down_revision: Union[str, None] = "819c8c6698fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_conversations", sa.Column("report_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        None, "email_conversations", "reports", ["report_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "email_conversations", type_="foreignkey")
    op.drop_column("email_conversations", "report_id")
    # ### end Alembic commands ###
