version: "3.8"

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
      - ./logs:/app/logs  # persistent logs directory