
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
      - ./logs:/app/logs  # persistent logs directory
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10" #Max 10 files of 50MB each