[tool.black]
line-length = 88
target-version = ["py311", "py312", "py313"]
include = '\.pyi?$'
exclude = '''
/(
    \.venv
  | __pycache__
  | build
  | dist
  | venv
  | env
)/
'''
[tool.isort]
profile = "black"
line_length = 88
skip = [
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "venv",
    "env",
]