/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/healthcheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_api_v1_healthcheck_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Users
         * @description List all users visible to the current user or
         *     return the single user if restricted.
         */
        get: operations["get_users_api_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Retrieve the authenticated user's profile information.
         */
        get: operations["get_current_user_info_api_v1_users_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Current User
         * @description Delete the authenticated user's account.
         */
        delete: operations["delete_current_user_api_v1_users_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync User
         * @description Synchronize the current user with the external Clerk service.
         */
        post: operations["sync_user_api_v1_users_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Available Search Profiles
         * @description Retrieve all search profiles available to the current user.
         */
        get: operations["get_available_search_profiles_api_v1_search_profiles_get"];
        put?: never;
        /**
         * Create Search Profile
         * @description Create a new search profile for the current user.
         */
        post: operations["create_search_profile_api_v1_search_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search-profiles/keywords/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Keyword Suggestions
         * @description Return keyword suggestions based on a list of input keywords.
         */
        post: operations["get_keyword_suggestions_api_v1_search_profiles_keywords_suggestions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search-profiles/{search_profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Search Profile
         * @description Retrieve a specific search profile by its UUID.
         */
        get: operations["get_search_profile_api_v1_search_profiles__search_profile_id__get"];
        /**
         * Update Search Profile
         * @description Update an existing search profile by its UUID.
         */
        put: operations["update_search_profile_api_v1_search_profiles__search_profile_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search-profiles/{search_profile_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Search Profile Overview
         * @description Retrieve an overview of articles for a given search profile.
         */
        get: operations["get_search_profile_overview_api_v1_search_profiles__search_profile_id__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search-profiles/{search_profile_id}/article/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Match Detail
         * @description Retrieve detailed match information for a specific article match.
         */
        get: operations["get_match_detail_api_v1_search_profiles__search_profile_id__article__match_id__get"];
        /**
         * Update Match Feedback
         * @description Update feedback for a specific match within a search profile.
         */
        put: operations["update_match_feedback_api_v1_search_profiles__search_profile_id__article__match_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search-profiles/{search_profile_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reports */
        get: operations["get_reports_api_v1_search_profiles__search_profile_id__reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Subscriptions */
        get: operations["get_all_subscriptions_api_v1_subscriptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emails/send/{recipient_email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trigger Email Sending */
        get: operations["trigger_email_sending_api_v1_emails_send__recipient_email__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/emails/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Send Report Email */
        get: operations["send_report_email_api_v1_emails_test_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vector-store/add-articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Articles To Vector Store
         * @description Add a list of articles to the vector store.
         */
        post: operations["add_articles_to_vector_store_api_v1_vector_store_add_articles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/article-matching/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Article Matching */
        post: operations["create_article_matching_api_v1_article_matching__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/summarize-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize All Articles
         * @description Summarize all articles in the database.
         */
        post: operations["summarize_all_articles_api_v1_articles_summarize_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trigger Pdf Creation */
        get: operations["trigger_pdf_creation_api_v1_articles_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topics By Search Profile
         * @description Get topics by search profile ID.
         */
        get: operations["get_topics_by_search_profile_api_v1_topics_get"];
        put?: never;
        /**
         * Create Topic By Search Profile
         * @description Create a topic by search profile ID.
         */
        post: operations["create_topic_by_search_profile_api_v1_topics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Topic
         * @description Delete a topic by ID.
         */
        delete: operations["delete_topic_api_v1_topics__topic_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Keywords By Topic Id
         * @description Get keywords by topic ID.
         */
        get: operations["get_keywords_by_topic_id_api_v1_keywords_get"];
        put?: never;
        /**
         * Create Keyword By Topic Id
         * @description Create a keyword by topic ID.
         */
        post: operations["create_keyword_by_topic_id_api_v1_keywords_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keywords/assign-keywords-to-articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Keywords To Articles
         * @description Assign keywords to articles in the background.
         */
        post: operations["assign_keywords_to_articles_api_v1_keywords_assign_keywords_to_articles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawler/trigger_crawling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Crawling */
        post: operations["trigger_crawling_api_v1_crawler_trigger_crawling_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawler/trigger_scraping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Scraping */
        post: operations["trigger_scraping_api_v1_crawler_trigger_scraping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawler/trigger_breaking_news_crawling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Newsapi Crawling */
        post: operations["trigger_newsapi_crawling_api_v1_crawler_trigger_breaking_news_crawling_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crawler/get_breaking_news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Breaking News */
        get: operations["get_breaking_news_api_v1_crawler_get_breaking_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report By Id */
        get: operations["get_report_by_id_api_v1_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArticleOverviewItem */
        ArticleOverviewItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Author */
            author: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Language */
            language: string;
            /** Category */
            category: string;
            /** Summary */
            summary: string | null;
            /** Sorting Order */
            sorting_order: number;
        };
        /** ArticleOverviewResponse */
        ArticleOverviewResponse: {
            /**
             * Search Profile Id
             * Format: uuid
             */
            search_profile_id: string;
            /** Articles */
            articles: components["schemas"]["ArticleOverviewItem"][];
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Keyword */
        Keyword: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Name */
            name: string;
        };
        /** KeywordSuggestionResponse */
        KeywordSuggestionResponse: {
            /** Suggestions */
            suggestions: string[];
        };
        /** MatchDetailResponse */
        MatchDetailResponse: {
            /**
             * Match Id
             * Format: uuid
             */
            match_id: string;
            /** Comment */
            comment: string | null;
            /** Sorting Order */
            sorting_order: number;
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Author */
            author: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Language */
            language: string;
            /** Category */
            category: string;
            /** Summary */
            summary: string | null;
        };
        /** MatchFeedbackRequest */
        MatchFeedbackRequest: {
            /** Comment */
            comment: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "bad source" | "false" | "no good matching" | "other";
            /** Ranking */
            ranking: number;
        };
        /** ReportDetailResponse */
        ReportDetailResponse: {
            /**
             * Search Profile Id
             * Format: uuid
             */
            search_profile_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Time Slot */
            time_slot?: string | null;
            /** S3 Key */
            s3_key: string;
            /** @default pending */
            status: components["schemas"]["ReportStatus"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** S3 Url */
            s3_url?: string | null;
        };
        /** ReportListResponse */
        ReportListResponse: {
            /** Reports */
            reports: components["schemas"]["ReportRead"][];
        };
        /** ReportRead */
        ReportRead: {
            /**
             * Search Profile Id
             * Format: uuid
             */
            search_profile_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Time Slot */
            time_slot?: string | null;
            /** S3 Key */
            s3_key: string;
            /** @default pending */
            status: components["schemas"]["ReportStatus"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * ReportStatus
         * @enum {string}
         */
        ReportStatus: "pending" | "uploaded" | "failed";
        /** SearchProfileCreateRequest */
        SearchProfileCreateRequest: {
            /** Name */
            name: string;
            /** Is Public */
            is_public: boolean;
            /**
             * Organization Emails
             * @default []
             */
            organization_emails: string[];
            /**
             * Profile Emails
             * @default []
             */
            profile_emails: string[];
            /**
             * Can Edit User Ids
             * @default []
             */
            can_edit_user_ids: string[];
            /**
             * Can Read User Ids
             * @default []
             */
            can_read_user_ids: string[];
            /** Subscriptions */
            subscriptions: components["schemas"]["SubscriptionSummary"][];
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Topics */
            topics: components["schemas"]["TopicCreateOrUpdateRequest"][];
        };
        /** SearchProfileDetailResponse */
        SearchProfileDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Is Public */
            is_public: boolean;
            /** Organization Emails */
            organization_emails: string[];
            /** Profile Emails */
            profile_emails: string[];
            /** Can Read User Ids */
            can_read_user_ids: string[];
            /** Is Reader */
            is_reader: boolean;
            /** Can Edit User Ids */
            can_edit_user_ids: string[];
            /** Is Editor */
            is_editor: boolean;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Is Owner */
            is_owner: boolean;
            /** Topics */
            topics: components["schemas"]["TopicResponse"][];
            /** Subscriptions */
            subscriptions: components["schemas"]["SubscriptionSummary"][];
            /** New Articles Count */
            new_articles_count: number;
        };
        /** SearchProfileUpdateRequest */
        SearchProfileUpdateRequest: {
            /** Name */
            name: string;
            /** Is Public */
            is_public: boolean;
            /**
             * Organization Emails
             * @default []
             */
            organization_emails: string[];
            /**
             * Profile Emails
             * @default []
             */
            profile_emails: string[];
            /**
             * Can Edit User Ids
             * @default []
             */
            can_edit_user_ids: string[];
            /**
             * Can Read User Ids
             * @default []
             */
            can_read_user_ids: string[];
            /** Subscriptions */
            subscriptions: components["schemas"]["SubscriptionSummary"][];
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Topics */
            topics: components["schemas"]["TopicCreateOrUpdateRequest"][];
        };
        /** SubscriptionSummary */
        SubscriptionSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Is Subscribed */
            is_subscribed: boolean;
        };
        /** Topic */
        Topic: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Search Profile Id
             * Format: uuid
             */
            search_profile_id: string;
        };
        /** TopicCreateOrUpdateRequest */
        TopicCreateOrUpdateRequest: {
            /** Name */
            name: string;
            /** Keywords */
            keywords: string[];
        };
        /** TopicResponse */
        TopicResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Keywords */
            keywords: string[];
        };
        /** UserEntity */
        UserEntity: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Clerk Id */
            clerk_id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Is Superuser */
            is_superuser: boolean;
            /** Organization Id */
            organization_id?: string | null;
            /** Organization Name */
            organization_name?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthcheck_api_v1_healthcheck_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"][] | components["schemas"]["UserEntity"];
                };
            };
        };
    };
    get_current_user_info_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    delete_current_user_api_v1_users_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
        };
    };
    sync_user_api_v1_users_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
        };
    };
    get_available_search_profiles_api_v1_search_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchProfileDetailResponse"][];
                };
            };
        };
    };
    create_search_profile_api_v1_search_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchProfileCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchProfileDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_keyword_suggestions_api_v1_search_profiles_keywords_suggestions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordSuggestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_search_profile_api_v1_search_profiles__search_profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchProfileDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_search_profile_api_v1_search_profiles__search_profile_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchProfileDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_search_profile_overview_api_v1_search_profiles__search_profile_id__overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_detail_api_v1_search_profiles__search_profile_id__article__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_profile_id: string;
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_match_feedback_api_v1_search_profiles__search_profile_id__article__match_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_profile_id: string;
                match_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchFeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reports_api_v1_search_profiles__search_profile_id__reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_subscriptions_api_v1_subscriptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionSummary"][];
                };
            };
        };
    };
    trigger_email_sending_api_v1_emails_send__recipient_email__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipient_email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_report_email_api_v1_emails_test_get: {
        parameters: {
            query: {
                /** @description Clerk User ID */
                clerk_id: string;
                /** @description Search Profile UUID */
                search_profile_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_articles_to_vector_store_api_v1_vector_store_add_articles_post: {
        parameters: {
            query?: {
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_article_matching_api_v1_article_matching__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    summarize_all_articles_api_v1_articles_summarize_all_post: {
        parameters: {
            query?: {
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_pdf_creation_api_v1_articles_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_topics_by_search_profile_api_v1_topics_get: {
        parameters: {
            query: {
                search_profile_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_topic_by_search_profile_api_v1_topics_post: {
        parameters: {
            query: {
                search_profile_id: string;
                topic_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_topic_api_v1_topics__topic_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_keywords_by_topic_id_api_v1_keywords_get: {
        parameters: {
            query: {
                topic_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Keyword"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_keyword_by_topic_id_api_v1_keywords_post: {
        parameters: {
            query: {
                topic_id: string;
                keyword_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Keyword"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_keywords_to_articles_api_v1_keywords_assign_keywords_to_articles_post: {
        parameters: {
            query?: {
                page_size?: number;
                score_threshold?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_crawling_api_v1_crawler_trigger_crawling_post: {
        parameters: {
            query?: {
                date_start?: string;
                date_end?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_scraping_api_v1_crawler_trigger_scraping_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_newsapi_crawling_api_v1_crawler_trigger_breaking_news_crawling_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_breaking_news_api_v1_crawler_get_breaking_news_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_report_by_id_api_v1_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
