"""Added columns in articles for translated title, content, and summary

Revision ID: 035d6eec4ca7
Revises: 82da1701bd5f
Create Date: 2025-06-21 11:39:53.242487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '035d6eec4ca7'
down_revision: Union[str, None] = '82da1701bd5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title_en', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('title_de', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('content_en', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('content_de', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('summary_en', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('summary_de', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'summary_de')
    op.drop_column('articles', 'summary_en')
    op.drop_column('articles', 'content_de')
    op.drop_column('articles', 'content_en')
    op.drop_column('articles', 'title_de')
    op.drop_column('articles', 'title_en')
    # ### end Alembic commands ###
