"""seachrprofile owner_id

Revision ID: 233ad2724f46
Revises: 2e9243e9b497
Create Date: 2025-06-10 14:10:37.077975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '233ad2724f46'
down_revision: Union[str, None] = '2e9243e9b497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_profiles', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'search_profiles', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search_profiles', type_='foreignkey')
    op.drop_column('search_profiles', 'owner_id')
    # ### end Alembic commands ###
