"""add matching_runs table

Revision ID: 469815c7416b
Revises: 3e8a9b88e46c
Create Date: 2025-06-27 14:48:49.792155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from sqlalchemy.schema import CreateSequence, DropSequence


# revision identifiers, used by Alembic.
revision: str = "469815c7416b"
down_revision: Union[str, None] = "3e8a9b88e46c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # build a SA Sequence
    seq = sa.Sequence("matching_run_counter_seq")
    # emit a CREATE SEQUENCE
    op.execute(CreateSequence(seq))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matching_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "counter",
            sa.Integer(),
            server_default=sa.text("nextval('matching_run_counter_seq')"),
            nullable=False,
        ),
        sa.Column(
            "algorithm_version",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("counter"),
    )

    op.add_column(
        "matches", sa.Column("matching_run_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_matches_matching_run_id"),
        "matches",
        ["matching_run_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "matches", "matching_runs", ["matching_runs_id"], ["id"]
    )
    op.add_column(
        "reports", sa.Column("matching_runs_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        None, "reports", "matching_runs", ["matching_runs_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reports", type_="foreignkey")
    op.drop_column("reports", "matching_runs_id")
    op.drop_constraint(None, "matches", type_="foreignkey")
    op.drop_index(op.f("ix_matches_matching_run_id"), table_name="matches")
    op.drop_column("matches", "matching_run_id")
    op.drop_table("matching_runs")
    seq = sa.Sequence("matching_run_counter_seq")
    op.execute(DropSequence(seq))
    # ### end Alembic commands ###
