"""add gender to user

Revision ID: 7af6cf813735
Revises: efd92ff0b2df
Create Date: 2025-07-09 14:05:32.148734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "7af6cf813735"
down_revision: Union[str, None] = "efd92ff0b2df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "gender",
            sa.Enum("male", "female", "divers", name="gender_enum"),
            server_default="male",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gender")
    # ### end Alembic commands ###
