"""add gender to user

Revision ID: 7af6cf813735
Revises: efd92ff0b2df
Create Date: 2025-07-09 14:05:32.148734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from enum import Enum


# revision identifiers, used by Alembic.
revision: str = "7af6cf813735"
down_revision: Union[str, None] = "efd92ff0b2df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


class GenderEnum(str, Enum):
    male = "male"
    female = "female"
    other = "other"


gender_enum = sa.Enum(GenderEnum, name="gender_enum")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum.create(op.get_bind())
    op.add_column(
        "users",
        sa.Column("gender", gender_enum, nullable=True, server_default="male"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gender")
    gender_enum.drop(op.get_bind())
    # ### end Alembic commands ###
