"""add match_date to match

Revision ID: 94014cc0b0d7
Revises: 82da1701bd5f
Create Date: 2025-06-20 10:27:13.600841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "94014cc0b0d7"
down_revision: Union[str, None] = "82da1701bd5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches", sa.Column("match_date", sa.Date(), nullable=False)
    )
    op.create_index(
        op.f("ix_matches_match_date"), "matches", ["match_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_matches_match_date"), table_name="matches")
    op.drop_column("matches", "match_date")
    # ### end Alembic commands ###
