"""add_server_default_to_organization_emails

Revision ID: b947a2c9659d
Revises: 7af6cf813735
Create Date: 2025-07-09 22:44:04.547600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b947a2c9659d'
down_revision: Union[str, None] = '7af6cf813735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add server default to organization_emails column
    op.alter_column(
        'search_profiles',
        'organization_emails',
        server_default='{}',
        existing_type=sa.ARRAY(sa.VARCHAR()),
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove server default from organization_emails column
    op.alter_column(
        'search_profiles',
        'organization_emails',
        server_default=None,
        existing_type=sa.ARRAY(sa.VARCHAR()),
        existing_nullable=True
    )
    # ### end Alembic commands ###
