services:
  qdrant:
    image: qdrant/qdrant:v1.14.0
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__API_KEY=QDRANT_SECRET_KEY

  backend:
    container_name: api
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    shm_size: "2g"
    restart: always
    depends_on:
      - postgres
      - qdrant
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ../apps/api:/app
    logging:
      driver: json-file
      options:
        max-size: "50m" # maximum size of each log file 50MB
        max-file: "10"

  scheduler:
    container_name: scheduler 
    build:
      context: ../apps/scheduler
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mediamind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  qdrant_data:
  postgres_data:
  redis_data:
