services:
  db:
    image: postgres:latest
    container_name: eutopdb-dev
    environment:
      POSTGRES_USER: eutop_dev
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: mediamind
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
