services:
  qdrant:
    image: qdrant/qdrant:v1.14.0
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - backend_logs_volumes:/app/logs # persistent logs directory
    logging:
      driver: json-file
      options:
        max-size: "50m" # maximum size of each log file 50MB
        max-file: "10"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mediamind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  qdrant_data:
  backend_logs_volumes:
    driver: local
  postgres_data:
