export default function useSearchProfile() {
  return {
    id: "1a2b3c4d-uuid-1",
    name: "BMW HR",
    organization_emails: [
      "abc@example.com",
      "def@example.com",
      "hr@bmw-group.com",
      "recruiting@bmw.com",
      "careers@bmw-group.com",
      "talent@bmw.com",
      "hr-europe@bmw.com",
      "hr-munich@bmw.com",
      "hr-berlin@bmw.com",
      "hr-leipzig@bmw.com",
      "hr-dingolfing@bmw.com",
      "hr-regensburg@bmw.com",
      "hr-landshut@bmw.com",
      "internships@bmw-group.com",
      "graduates@bmw.com",
    ],
    profile_emails: [
      "ghi@example.com",
      "jkl@example.com",
      "j.schmidt@bmw.com",
      "m.mueller@bmw-group.com",
      "s.wagner@bmw.com",
      "t.becker@bmw-group.com",
      "a.hoffmann@bmw.com",
      "l.fischer@bmw-group.com",
      "n.weber@bmw.com",
      "p.schulz@bmw-group.com",
      "c.meyer@bmw.com",
      "b.schneider@bmw-group.com",
      "r.wolf@bmw.com",
      "d.richter@bmw-group.com",
      "k.schaefer@bmw.com",
    ],
    public: true,
    editable: false,
    is_editable: true,
    owner: "user-uuid-123",
    is_owner: true,
    subscriptions: [
      { id: 1, name: "Spiegel" },
      { id: 2, name: "Süddeutsche Zeitung" },
    ],
    topics: [
      {
        name: "Battery",
        keywords: [
          "Lithium",
          "Power",
          "Tesla",
          "Energy",
          "Charging",
          "Storage",
          "Electric",
          "Capacity",
        ],
      },
      {
        name: "Recruiting",
        keywords: [
          "Talent",
          "Onboarding",
          "Interviews",
          "Hiring",
          "Candidates",
          "Recruitment",
          "Staffing",
          "Retention",
        ],
      },
      {
        name: "Compliance",
        keywords: [
          "GDPR",
          "Regulations",
          "Privacy",
          "Legal",
          "Policies",
          "Standards",
          "Audit",
          "Certification",
        ],
      },
      {
        name: "Payroll",
        keywords: [
          "Salary",
          "Benefits",
          "Taxes",
          "Compensation",
          "Bonuses",
          "Deductions",
          "Payments",
          "Accounting",
        ],
      },
    ],
  };
}
