"""add pdf_as_link to organizations

Revision ID: 105a3eb259e5
Revises: 7af6cf813735
Create Date: 2025-07-11 12:32:49.322971

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "105a3eb259e5"
down_revision: Union[str, None] = "7af6cf813735"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("pdf_as_link", sa.Boolean(), nullable=False, default=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "pdf_as_link")
    # ### end Alembic commands ###
