"""add breaking_news to users

Revision ID: 36d16a1fbaec
Revises: 7af6cf813735
Create Date: 2025-07-11 12:58:06.922324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "36d16a1fbaec"
down_revision: Union[str, None] = "7af6cf813735"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "breaking_news",
            sa.Boolean(),
            nullable=False,
            server_default=sa.sql.expression.true())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "breaking_news")
    # ### end Alembic commands ###
