name: Backend deploy

on:
  push:
    branches:
      - master
env:
  DOCKER_IMAGE: eutop/backend 
  DOCKERFILE_PATH: ./backend/Dockerfile
  DOCKER_CONTEXT: ./backend

jobs:
  backend-premerge:
    uses: ./.github/workflows/backend-premerge.yml
  api-types:
    uses: ./.github/workflows/generate-api-types.yml

  docker-build-push:
    needs: backend-premerge
    uses: ./.github/workflows/docker-build-push.yml
    with:
      image_name: ${{ DOCKER_IMAGE }}
      dockerfile_path: ${{ DOCKERFILE_PATH }}
      context: ${{ DOCKER_CONTEXT }}
    secrets:
      registry_username: ${{ secrets.DOCKER_USERNAME }}
      registry_password: ${{ secrets.DOCKER_PASSWORD }}

