name: Backend deploy

on:
  push:
    branches:
      - master
env:
  DOCKER_IMAGE: eutop/backend
  DOCKERFILE_PATH: ./backend/Dockerfile
  DOCKER_CONTEXT: ./backend

jobs:
  backend-premerge:
    uses: ./.github/workflows/backend-premerge.yml

  api-types:
    uses: ./.github/workflows/generate-api-types.yml
    secrets:
      API_TYPES_EMAIL: ${{ secrets.API_TYPES_EMAIL }}
      API_TYPES_PAT_TOKEN: ${{ secrets.API_TYPES_PAT_TOKEN }}
