name: Backend deploy

on:
  push:
    branches:
      - master

jobs:
  backend-premerge:
    uses: ./.github/workflows/backend-premerge.yml

  api-types:
    uses: ./.github/workflows/generate-api-types.yml
    secrets:
      API_TYPES_EMAIL: ${{ secrets.API_TYPES_EMAIL }}
      API_TYPES_PAT_TOKEN: ${{ secrets.API_TYPES_PAT_TOKEN }}

  build-and-push:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      image_name: ecr-mediamind
      image_tag: latest
      dockerfile_path: ./backend/Dockerfile
      context: ./backend
      aws_region: eu-central-1
      ecr_registry: 313193269185.dkr.ecr.eu-central-1.amazonaws.com
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
