name: Backend pre-merge

on:
  pull_request:
    paths:
      - "backend/**"
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check formatting with Black
        run: black --check app

      - name: Check import sorting with isort
        run: isort --check-only app

      - name: Run flake8 lint
        run: flake8 app

      - name: Run tests
        run: pytest

