name: Backend pre-merge

on:
  workflow_call:
  pull_request:
    paths:
      - "backend/**"

jobs:
  setup:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.13"]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 black isort

  lint:
    needs: setup
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.13"]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Check formatting with Black
        run: black --check app

      - name: Check import sorting with isort
        run: isort --check-only app

      - name: Run flake8 lint
        run: flake8 app

  test:
    needs: setup
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.13"]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install testing tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: PYTHONPATH=app pytest tests/* --cov=app --cov-report=xml --cov-report=term --cov-fail-under=75

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./backend/coverage.xml
          retention-days: 5
