name: Backend deploy

on:
  push:
    branches:
      - master

jobs:
  backend-premerge:
    uses: ./.github/workflows/backend-premerge.yml

  api-types:
    uses: ./.github/workflows/generate-api-types.yml
    secrets:
      API_TYPES_EMAIL: ${{ secrets.API_TYPES_EMAIL }}
      API_TYPES_PAT_TOKEN: ${{ secrets.API_TYPES_PAT_TOKEN }}

  build-and-push:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      image_name: ecr-mediamind
      image_tag: latest
      dockerfile_path: ./backend/Dockerfile
      context: ./backend
      aws_region: eu-central-1
      ecr_registry: 313193269185.dkr.ecr.eu-central-1.amazonaws.com
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  apply-migrations-dev:
    uses: ./.github/workflows/apply-migrations.yml
    secrets:
      DB_SERVER: ${{ secrets.DEV_DB_SERVER }}
      DB_PORT: ${{ secrets.DEV_DB_PORT }}
      DB_USER: ${{ secrets.DEV_DB_USER }}
      DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      DB_NAME: ${{ secrets.DEV_DB_NAME }}

  apply-migrations-prod:
    uses: ./.github/workflows/apply-migrations.yml
    secrets:
      DB_SERVER: ${{ secrets.PROD_DB_SERVER }}
      DB_PORT: ${{ secrets.PROD_DB_PORT }}
      DB_USER: ${{ secrets.PROD_DB_USER }}
      DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
      DB_NAME: ${{ secrets.PROD_DB_NAME }}

  ecs-deploy:
    needs: build-and-push
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Force new ECS deployment (prod)
        run: |
          aws ecs update-service \
            --cluster mediamind-cluster \
            --service mediamind-service \
            --force-new-deployment \
            --region eu-central-1

      - name: Force new ECS deployment (dev)
        run: |
          aws ecs update-service \
            --cluster mediamind-cluster \
            --service mediamind-service-dev \
            --force-new-deployment \
            --region eu-central-1
