name: Backend pre-merge

on:
  pull_request:
    paths:
      - "apps/backend/**"
  workflow_call:

jobs:
  python-premerge:
    uses: ./.github/workflows/python-premerge.yml
    with:
      workdir: ./apps/backend

  check-alembic:
    needs: python-premerge
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./apps/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Copy env
        run: cp .env.example .env

      - name: Alembic dry-run
        run: alembic upgrade head --sql
