name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: Dockerfile
      context:
        required: false
        type: string
        default: .

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Generate image tag
      id: tag
      run: echo "::set-output name=tag::$(date +'%Y-%m-%d')"
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile_path }}
        push: true
        tags: |
          ${{ inputs.registry }}/${{ inputs.image_name }}:${{ steps.tag.outputs.tag }}
          ${{ inputs.registry }}/${{ inputs.image_name }}:latest
