name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: false
        type: string
        default: latest
      dockerfile_path:
        required: false
        type: string
        default: Dockerfile
      context:
        required: false
        type: string
        default: .
      registry:
        required: false
        type: string
        default: ghcr.io 

    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ secrets.registry_username }}
        password: ${{ secrets.registry_password }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile_path }}
        push: true
        tags: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}

