name: Frontend pre-merge

on:
  pull_request:
    paths:
      - "frontend/**"
  workflow_call:

jobs:
  premerge:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check code format
        run: npx prettier --check .

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test
