name: Frontend deploy

on:
  push:
    branches:
      - master
env:
  DOCKER_IMAGE: eutop/frontend
  DOCKERFILE_PATH: ./frontend/Dockerfile
  DOCKER_CONTEXT: ./frontend

jobs:
  frontend-premerge:
    uses: ./.github/workflows/frontend-premerge.yml
