name: Frontend deploy

on:
  push:
    branches:
      - master
env:
  DOCKER_IMAGE: eutop/frontend
  DOCKERFILE_PATH: ./apps/frontend/Dockerfile
  DOCKER_CONTEXT: ./apps/frontend

jobs:
  frontend-premerge:
    uses: ./.github/workflows/frontend-premerge.yml
