name: Generate API types

on:
  workflow_call:

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      working-directory: ./backend

    - name: Extract OpenAPI spec
      run: python extract-openapi.py --app-dir ../ app.main:app --out /tmp/openapi.json
      working-directory: ./backend/scripts

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install openapi-typescript
      run: |
        npm install openapi-typescript typescript

    - name: Generate Typescript types
      run: |
        mkdir -p frontend/api-types/
        npx openapi-typescript /tmp/openapi.json -o ./frontend/types/api-types-v1.d.ts

    - name: Commit 
      run: |
        git config --global user.name 'API types'
        git config --global user.email 'api-types@mediamind.eu'
        git commit -am "feat: generated new API types"
        git push

