name: Scheduler deploy

on:
  push:
    branches:
      - master

jobs:
  scheduler-premerge:
    uses: ./.github/workflows/scheduler-premerge.yml
  build-and-push:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      image_name: ecr-mediamind-scheduler
      image_tag: latest
      dockerfile_path: ./apps/scheduler/Dockerfile
      context: ./apps/scheduler
      aws_region: eu-central-1
      ecr_registry: 313193269185.dkr.ecr.eu-central-1.amazonaws.com
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  ecs-deploy:
    needs: build-and-push
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Force new ECS deployment (prod)
        run: |
          aws ecs update-service \
            --cluster mediamind-cluster \
            --service mediamind-scheduler \
            --force-new-deployment \
            --region eu-central-1

      - name: Force new ECS deployment (dev)
        run: |
          aws ecs update-service \
            --cluster mediamind-cluster \
            --service mediamind-scheduler-dev \
            --force-new-deployment \
            --region eu-central-1
