name: Test Build and Push

on:
  push:

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      image_name: ecr-mediamind
      image_tag: test
      dockerfile_path: ./backend/Dockerfile
      context: ./backend
      aws_region: eu-central-1
      ecr_registry: 313193269185.dkr.ecr.eu-central-1.amazonaws.com
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}